alibaba/lowcode-demo

package.json

解决一下 issues 中的问题：
- https://github.com/alibaba/lowcode-engine/issues/30
- https://github.com/alibaba/lowcode-engine/issues/56
- https://github.com/alibaba/lowcode-engine/issues/68

feat: 🎸 升级出码插件, 接入 CodeSandbox 预览, 并解决一些出码预览的问题

---

package.json

- 使用 1.0.2 的 manual 组件，避免被跨域政策拦截

feat: update dependency

---

README.md
package.json
public/index.ejs
src/sample-plugins/scenario-switcher/index.tsx
src/scenarios/basic-fusion-with-single-component/index.ts
src/scenarios/basic-fusion/index.ts
src/scenarios/custom-initialization/index.tsx
src/scenarios/index/index.ts
src/scenarios/node-extended-actions/assets.json
src/scenarios/node-extended-actions/index.ts
src/scenarios/node-extended-actions/plugin.tsx
src/scenarios/node-extended-actions/schema.json
src/universal/scenarios.json

1. 增加操作节点操作项；
2. 升级引擎版本至 1.0.3；

feat: add scenario for extending node actions

---

public/index.ejs
src/sample-plugins/delete-hidden-transducer/index.ts
src/universal/plugin.tsx
src/universal/utils.ts

Need https://github.com/alibaba/lowcode-engine/pull/287 合并之后发布新的版本，DEMO 更新引擎版本。

fix: fixed dialog in preview not rendering when hidden in design

---

package.json

fix: 🐛 解决出码插件的问题

---

package.json

Fix: https://github.com/alibaba/lowcode-engine/issues/367

chore: update schema plugin dependency

---

package.json

chore: bump into next version

---

package.json

fix: https://github.com/alibaba/lowcode-engine/issues/416

chore: update lowcode-plugin-code-editor

---

package.json

fix: https://github.com/alibaba/lowcode-engine/issues/466
currently available at:
https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.19/build/index.html

chore: update dependency and bump version

---

package.json
src/sample-plugins/set-ref-prop/index.tsx
src/universal/plugin.tsx

feat: add refId prop for Component

---

package.json

Fix https://github.com/alibaba/lowcode-engine/issues/803

chore: fix @alilc/lowcode-plugin-code-editor error

---

src/preview.tsx
src/sample-plugins/delete-hidden-transducer/index.ts
src/sample-plugins/scenario-switcher/index.tsx
src/sample-plugins/set-ref-prop/index.tsx
src/scenarios/antd-pro-with-formily/index.ts
src/scenarios/basic-antd/index.ts
src/scenarios/basic-fusion-with-single-component/assets.json
src/scenarios/basic-fusion-with-single-component/index.ts
src/scenarios/basic-fusion/assets.json
src/scenarios/basic-fusion/index.ts
src/scenarios/custom-initialization/index.tsx
src/scenarios/index/index.ts
src/scenarios/next-pro/index.ts
src/scenarios/node-extended-actions/index.ts
src/universal/plugin.tsx

1. 修复当有 search 时，获取场景名称不对；
2. 修改传递 DataSourcePane 参数为推荐方式；
3. 删除不必要透出的引擎 init 参数；
4. 将assets.json 中老的 experimental 的写法改为 configure.advanced 方式；
5. 部分代码小重构；

refactor: bunch of code refactorings

---

src/scenarios/basic-antd/plugin.tsx
src/scenarios/basic-fusion-with-single-component/plugin.tsx
src/scenarios/basic-fusion/plugin.tsx

已经 antd、fusion、fusion自定义，3 个场景补充了 refId 的代码

feat: 设计器 Demo 一些场景没有添加 refId，导致无法调用实例

---

demo-antd-pro-with-formily/src/index.ts
demo-basic-antd/package.json
demo-basic-fusion-with-single-component/package.json
demo-basic-fusion/package.json
demo-custom-initialization/package.json
demo-general/package.json
demo-next-pro/package.json
demo-node-extended-actions/package.json

fix: register formilyPlugin

---

demo-general/src/services/defaultPageSchema.json

fixed: https://github.com/alibaba/lowcode-engine/issues/1460

fix: fix the problem that Slot is not defined in output mode

---

demo-antd-pro-with-formily/src/services/assets.json
package.json

Close https://github.com/alibaba/lowcode-engine/issues/1273

feat: upgrade seada materials

---

demo-general/src/index.ts
demo-general/src/preview.tsx

fixed https://github.com/alibaba/lowcode-engine/issues/1528

feat: preview supports public data sources

---

demo-custom-initialization/src/services/assets.json
demo-general/src/services/assets.json

Reverts alibaba/lowcode-demo#107

Revert "feat: upgrade @alifd/pro-layout to @alifd/layout@2.0.5"

---

demo-antd-pro-with-formily/src/services/mockService.ts
demo-basic-antd/src/services/mockService.ts
demo-basic-fusion/src/services/mockService.ts
demo-custom-initialization/src/services/mockService.ts
demo-general/src/services/mockService.ts
demo-graph-x6/src/services/mockService.ts
demo-lowcode-component/src/services/mockService.ts
demo-next-pro/src/services/mockService.ts
demo-node-extended-actions/src/services/mockService.ts

fix typo setPackgesToLocalStorage => setPackagesToLocalStorage

fix: fix typo setPackgesToLocalStorage => setPackagesToLocalStorage

---

demo-custom-initialization/src/services/assets.json
demo-general/src/services/assets.json

Fixes https://github.com/alibaba/lowcode-engine/issues/1886

feat: update @alifd/layout to 2.0.11

---

demo-antd-pro-with-formily/src/services/mockService.ts
demo-basic-antd/src/services/mockService.ts
demo-basic-fusion/src/services/mockService.ts
demo-custom-initialization/src/services/mockService.ts
demo-general/src/services/mockService.ts
demo-graph-x6/src/services/mockService.ts
demo-lowcode-component/src/services/mockService.ts
demo-next-pro/src/services/mockService.ts
demo-node-extended-actions/src/services/mockService.ts

TransformStage已废弃，使用最新的IPublicEnumTransformStage

chore: TransformStage replace IPublicEnumTransformStage

---

demo-custom-initialization/src/services/assets.json
demo-general/src/services/assets.json

更新@alifd/layout至2.0.12。下架拓展区域模块

fix: 更改自然布局版本

---

demo-custom-initialization/src/services/assets.json
demo-general/src/services/assets.json

ref: https://github.com/alibaba/lowcode-materials/pull/51

refactor: update fusion ui version to fix several bugs

---

demo-basic-antd/src/services/assets.json

fixed: https://github.com/alibaba/lowcode-engine/issues/1821

feat: update antd to 4.23.0 version
